# Air configuration file for Simple MCP Market Data Server
# Air is a live reload tool for Go development
# Install with: go install github.com/cosmtrek/air@latest

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
# Array of commands to run before each build
pre_cmd = []

# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./tmp/main ./cmd/main.go"

# Array of commands to run after ^C
post_cmd = []

# Binary file yields from `cmd`.
bin = "tmp/main"

# Customize binary, can setup environment variables when run your app.
full_bin = "./tmp/main"

# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html", "json", "yaml", "yml", "toml", "env"]

# Ignore these filename extensions or directories.
exclude_dir = ["assets", "tmp", "vendor", "testdata", "bin", "dist", "docs", ".git", ".vscode", ".idea", "node_modules"]

# Watch these directories if you specified.
include_dir = []

# Watch these files.
include_file = []

# Exclude files.
exclude_file = []

# Exclude specific regular expressions.
exclude_regex = ["_test\\.go"]

# Exclude unchanged files.
exclude_unchanged = true

# Follow symlink for directories
follow_symlink = false

# This log file places in your tmp_dir.
log = "errors.log"

# Poll files for changes instead of using fsnotify.
poll = false

# Poll interval (defaults to the minimum interval of 500ms).
poll_interval = 500 # ms

# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 0 # ms

# Stop running old binary when build errors occur.
stop_on_error = false

# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = true

# Delay after sending Interrupt signal
kill_delay = "0s"

# Rerun binary or not
rerun = true

# Delay after each executions
rerun_delay = 500

# Add additional arguments when running binary (bin/full_bin). Will run './tmp/main hello world'.
args_bin = []

[log]
# Show log time
time = true

# Only show main log (hide build log)
main_only = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = false

[screen]
# Clear screen on each run
clear_on_rebuild = false

# Enable to skip unnecessary build
keep_scroll = true
